### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by demonlj** [EagleW/PaperRobot#7]
system

> ubuntu 
> Linux pve-ubuntu 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

python train.py --data_path data/pubmed_abstract --model_dp abstract_model/

Epoch 0/99
Traceback (most recent call last):
  File "train.py", line 236, in <module>
    batch_o_t, teacher_forcing_ratio=1)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/seq2seq.py", line 18, in forward
    stopwords, sflag)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/Decoder.py", line 134, in forward
    max_source_oov, term_output, term_id, term_mask)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/Decoder.py", line 68, in decode_step
    term_context, term_attn = self.memory(_h.unsqueeze(0), term_output, term_mask, cov_mem)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/utils.py", line 32, in forward
    e_t = self.vt_layers[i](torch.tanh(enc_proj + dec_proj).view(batch_size * max_enc_len, -1))
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0

**Comment by EagleW** [comment]
Thank you for your interest. Which pytorch version did you use? Have you used cuda?

**Comment by demonlj** [comment]
Thanks a lot for your kind reply.
pytorch version: torch-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
I'm not sure wether cuda is used. Follow your instruction, I did not find the requirements on cuda.

**Comment by EagleW** [comment]
I mean have you use gpu?

**Comment by EagleW** [comment]
The default setting is to use GPU

**Comment by demonlj** [comment]
Maybe I need to disable the GPU option, because it takes a lot time to run the script. so, i move the script from osx to remote server

**Comment by demonlj** [comment]
How to disable the GPU option?

**Comment by EagleW** [comment]
Emm, I haven't tried to use cpu, I recommend to use the gpu, you can diable it by adding --gpu 0

**Comment by demonlj** [comment]
no lucky.

`Traceback (most recent call last):
  File "train.py", line 236, in <module>
    batch_o_t, teacher_forcing_ratio=1)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/seq2seq.py", line 18, in forward
    stopwords, sflag)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/Decoder.py", line 134, in forward
    max_source_oov, term_output, term_id, term_mask)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/Decoder.py", line 68, in decode_step
    term_context, term_attn = self.memory(_h.unsqueeze(0), term_output, term_mask, cov_mem)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/sync/ubuntu/PaperRobot-master/New paper writing/memory_generator/utils.py", line 32, in forward
    e_t = self.vt_layers[i](torch.tanh(enc_proj + dec_proj).view(batch_size * max_enc_len, -1))
RuntimeError: [enforce fail at CPUAllocator.cpp:56] posix_memalign(&data, gAlignment, nbytes) == 0. 12 vs 0`

**Comment by EagleW** [comment]
Let me test on my computer

**Comment by EagleW** [comment]
I haven't encountered the same problem, maybe you can try a smaller batch size by setting --batch_size 10?

**Comment by demonlj** [comment]
Lucky for me. It's running now with the setting --batch_size 10

**Comment by EagleW** [comment]
Great, I think maybe it's out of memory

**Comment by EagleW** [comment]
I found that the previous error is a CPU OOM message https://github.com/pytorch/pytorch/pull/20618
